### ISSUE TITLE
Enabling / disabling devices seems to be broken

### ISSUE THREAD

**Issue by eliaskg** [leolabs/ableton-js#112]
To reproduce, place a plugin or any other effect device on the Master track and run

```
const song = await ableton.song
const master_track = await song.get('master_track')
const devices = await master_track.get('devices')
  
devices.forEach(async function(device) {
  await device.set("is_active", false)
})
```

This results in

```
return functionCallback.rej(new Error(data.data));
                                        ^

Error: can't set attribute
    at Ableton.handleUncompressedMessage (/Users/elias/Documents/Code/Scripts/ableton-js/node_modules/ableton-js/index.js:271:41)
    at Ableton.handleIncoming (/Users/elias/Documents/Code/Scripts/ableton-js/node_modules/ableton-js/index.js:250:22)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:930:8)
```

`ableton-js/src/ns/device.ts` lists **'name'** and **'is_active'** as settable properties. Setting the name (e.g. on an effect rack) works fine.

Tested on the latest version of ableton-js and Live 11.3.13

**Comment by leolabs** [comment]
That's a good catch! It seems like the `is_active` property is actually read-only. I'll change this in the next update.

To control whether a device is on or off, you can get the device's list of parameters. The first one controls its `active` state:

```ts
const masterTrack = await ableton.song.get("master_track");
const devices = await masterTrack.get("devices");

for (const device of devices) {
  const params = await device.get("parameters");
  await params[0].set("value", 0); // 0 disables the device, 1 enables it
}
```

I hope this helps!
